#!/bin/zsh
 
function extractPorts() {
    if [[ -z "$1" ]];then
        echo
        echo "[-] Pass a file as argument!"
        echo
        echo "extractPorts [File]"
        return -1
    fi
 
    if [[ ! -f "$1" ]];then
        echo "[-] File not found!"
        return -1
    fi
 
    echo "[+] Ports copied"
    egrep -wo "([6]([5]{2}[0-3][0-5]|[0-4][0-9]{3})|[1-5]{0,1}[0-9]{0,4})/open" $1 | cut -d "/" -f1 | xargs | tr -d '\n' | tr ' ' ',' | xclip -selection clipboard
}