#!/usr/bin/zsh

function mkwork() {
	if [ -z $1 ];then
		echo "(?) mkwork [machineName]"
		return 1
	fi

	machineName=$1
	mkdir -p ${machineName}/enumeration/nmap
	mkdir -p ${machineName}/upload
	mkdir -p ${machineName}/downloads
	mkdir -p ${machineName}/tools
	mkdir -p ${machineName}/exploits
	mkdir -p ${machineName}/discoveries
	cd ~/${machineName}/enumeration/nmap
}
