#!/usr/bin/zsh

function mkwork() {
	if [ -z $1 ];then
		echo "(?) mkwork [machineName]"
		return 1
	fi

	machineName=$1
	mkdir -p HTB/${machineName}/{enumeration/nmap,upload,downloads,tools,exploits,discoveries}
	cd HTB/${machineName}/enumeration/nmap
}
